<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2020/2/15 0015
 * Time: 18:24
 */

namespace app\user\controller;


use think\Controller;
use think\Session;

class Filter extends Controller
{


    public function _initialize()
    {
//        parent::_initialize(); // TODO: Change the autogenerated stub

        if (Session::get('user_name') == null) {//未登录
            $this->redirect('/login');
        } else {
//            echo '登录正常';
        }

    }


    public function getUserName()
    {

        $userName = Session::get('user_name');
        if ($userName != null) {
            return $userName;
        } else {
            $this->redirect('/login');
        }

    }

}